[registries.crates-io]
protocol = "sparse"

[source.crates-io]
replace-with = "rsproxy"

[source.rsproxy]
registry = "sparse+https://rsproxy.cn/crates.io-index/"

[http]
multiplexing = false
timeout = 600
